### ISSUE TITLE
Allow "ApplicationId" in StackName

### ISSUE THREAD

**Issue by conjuncte** [zalando/lizzy#48]
Currently it's not possible to specify ApplicationId parameter in StackName like
```
SenzaInfo:
  StackName: "{{Arguments.ApplicationId}}"
  Parameters:
    - ImageVersion:
        Description: "Docker image version of the application from pierone."
    - ApplicationId:
        Description: "Application ID from kio"
```

However, it's valid YAML definition for `senza 1.0.30`. I can create a stack using senza, moreover lizzy also creates a stack, but reports failure to Jenkins.

I've checked following configuration:

lizzy-server  ImageVersion is 223
Lizzy Client 1.1.20160210 (got from `lizzy --version`)

Logs from Jenkins:
```
$ /bin/bash /tmp/hudson3606752098391816739.sh
Deploying App version 0.1.79f47f48 to Staging...
Fetching authentication token.. . OK
Requesting new stack.. OK
Stack ID: {{Arguments.ApplicationId}}-0o1o79f47f48T20160216093813
Waiting for new stack...
 LIZZY:DEPLOYING
 . LIZZY:REMOVED
Stack was removed before deployment finished.
 EXCEPTION OCCURRED: 1
Deployment has been failed. See logs:
Fetching authentication token.. . OK
Requesting new stack.. OK
Stack ID: {{Arguments.ApplicationId}}-0o1o79f47f48T20160216093813
Waiting for new stack...
 LIZZY:DEPLOYING
 . LIZZY:REMOVED
Stack was removed before deployment finished.
 EXCEPTION OCCURRED: 1
```
